server {
    listen 80;
    server_name veeb.kollanokad.praktika veeb1.kollanokad.praktika veeb2.kollanokad.praktika;
    root /var/www/wordpress;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
    }
}
