[ubuntu]
veeb1 ansible_host=172.18.30.40
veeb2 ansible_host=172.18.30.41
koormusjaotur ansible_host=172.18.30.42

[centos]
docker ansible_host=172.18.30.50
andmebaas ansible_host=172.18.30.51
monitor ansible_host=172.18.30.52
siem ansible_host=172.18.30.53

[linux_servers:children]
ubuntu
centos
